-- Add question_number column to practice_questions table
ALTER TABLE practice_questions 
ADD COLUMN question_number INTEGER;

-- Update existing OS questions with their correct order (1-50) based on topic-wise organization
UPDATE practice_questions 
SET question_number = 1 
WHERE question = 'Which of the following is not a function of an operating system?';

UPDATE practice_questions 
SET question_number = 2 
WHERE question = 'The main purpose of an operating system is to:';

UPDATE practice_questions 
SET question_number = 3 
WHERE question = 'Which of the following is a type of system software?';

UPDATE practice_questions 
SET question_number = 4 
WHERE question = 'Which of these is not a valid example of an OS?';

UPDATE practice_questions 
SET question_number = 5 
WHERE question = 'An OS acts as an interface between:';

UPDATE practice_questions 
SET question_number = 6 
WHERE question = 'What is a process?';

UPDATE practice_questions 
SET question_number = 7 
WHERE question = 'Which of the following is not a process state?';

UPDATE practice_questions 
SET question_number = 8 
WHERE question = 'The Process Control Block (PCB) does not contain:';

UPDATE practice_questions 
SET question_number = 9 
WHERE question = 'Context switching means:';

UPDATE practice_questions 
SET question_number = 10 
WHERE question = 'Which of the following is used for interprocess communication?';

UPDATE practice_questions 
SET question_number = 11 
WHERE question = 'Which of the following is non-preemptive scheduling?';

UPDATE practice_questions 
SET question_number = 12 
WHERE question = 'In Round Robin scheduling, time quantum means:';

UPDATE practice_questions 
SET question_number = 13 
WHERE question = 'Which algorithm can lead to starvation?';

UPDATE practice_questions 
SET question_number = 14 
WHERE question = 'Which scheduling algorithm gives minimum average waiting time?';

UPDATE practice_questions 
SET question_number = 15 
WHERE question = 'Priority scheduling can suffer from:';

UPDATE practice_questions 
SET question_number = 16 
WHERE question = 'Which of the following is a synchronization tool?';

UPDATE practice_questions 
SET question_number = 17 
WHERE question = 'Busy waiting occurs in:';

UPDATE practice_questions 
SET question_number = 18 
WHERE question = 'Which of the following solves critical section problems?';

UPDATE practice_questions 
SET question_number = 19 
WHERE question = 'The bounded buffer problem is an example of:';

UPDATE practice_questions 
SET question_number = 20 
WHERE question = 'Which of the following ensures mutual exclusion?';

UPDATE practice_questions 
SET question_number = 21 
WHERE question = 'What is a deadlock?';

UPDATE practice_questions 
SET question_number = 22 
WHERE question = 'Deadlock can occur when:';

UPDATE practice_questions 
SET question_number = 23 
WHERE question = 'Which of the following is a deadlock prevention technique?';

UPDATE practice_questions 
SET question_number = 24 
WHERE question = 'Deadlock detection uses:';

UPDATE practice_questions 
SET question_number = 25 
WHERE question = 'Banker''s algorithm is used for:';

UPDATE practice_questions 
SET question_number = 26 
WHERE question = 'Paging is used for:';

UPDATE practice_questions 
SET question_number = 27 
WHERE question = 'In paging, the address generated by CPU is called:';

UPDATE practice_questions 
SET question_number = 28 
WHERE question = 'Page fault occurs when:';

UPDATE practice_questions 
SET question_number = 29 
WHERE question = 'Thrashing occurs when:';

UPDATE practice_questions 
SET question_number = 30 
WHERE question = 'Demand paging uses:';

UPDATE practice_questions 
SET question_number = 31 
WHERE question = 'A page replacement algorithm replaces:';

UPDATE practice_questions 
SET question_number = 32 
WHERE question = 'Optimal page replacement is:';

UPDATE practice_questions 
SET question_number = 33 
WHERE question = 'In segmentation, each segment has:';

UPDATE practice_questions 
SET question_number = 34 
WHERE question = 'Fragmentation in memory occurs due to:';

UPDATE practice_questions 
SET question_number = 35 
WHERE question = 'Internal fragmentation occurs in:';

UPDATE practice_questions 
SET question_number = 36 
WHERE question = 'External fragmentation occurs in:';

UPDATE practice_questions 
SET question_number = 37 
WHERE question = 'The main function of file system is to:';

UPDATE practice_questions 
SET question_number = 38 
WHERE question = 'FAT stands for:';

UPDATE practice_questions 
SET question_number = 39 
WHERE question = 'Which of the following is not a file access method?';

UPDATE practice_questions 
SET question_number = 40 
WHERE question = 'The root directory of Windows is represented by:';

UPDATE practice_questions 
SET question_number = 41 
WHERE question = 'Disk scheduling algorithm that gives minimum average seek time:';

UPDATE practice_questions 
SET question_number = 42 
WHERE question = 'In SCAN scheduling, the disk arm:';

UPDATE practice_questions 
SET question_number = 43 
WHERE question = 'The OS module that manages input/output devices is:';

UPDATE practice_questions 
SET question_number = 44 
WHERE question = 'Spooling stands for:';

UPDATE practice_questions 
SET question_number = 45 
WHERE question = 'Which device is used for virtual memory?';

UPDATE practice_questions 
SET question_number = 46 
WHERE question = 'A system call is used to:';

UPDATE practice_questions 
SET question_number = 47 
WHERE question = 'The kernel is:';

UPDATE practice_questions 
SET question_number = 48 
WHERE question = 'A shell is:';

UPDATE practice_questions 
SET question_number = 49 
WHERE question = 'UNIX is a:';

UPDATE practice_questions 
SET question_number = 50 
WHERE question = 'Which of the following is not a type of OS?';
